name: chrishennkens
favicon: null
layout_spectrum: 0.29575910442508757
typography_spectrum: 0.5329161416739225
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5065029510296881
  lightness: 0.34601379884406924
  saturation: 0.6690186886116862
  rhythmicContrast: 0.27964591700583696
purpose: []
